data:
	gcc programm.c stack.c set.c queue.c hash_table.c -o dataBase.out
prog:
	gcc main.c -o program
fileman:
	gcc fileman.c stack.c set.c queue.c hash_table.c -o fileman
reader:
	gcc reader.c stack.c set.c queue.c hash_table.c -o reader
